### ISSUE TITLE
has pkg mod error when 'go get'

### ISSUE THREAD

**Issue by reducm** [antavelos/terminews#18] opened 2020-02-13 11:11 UTC
```bash
$ go get -d github.com/antavelos/terminews
...
# and got issues below

go: finding github.com/nsf/termbox-go latest
# github.com/antavelos/terminews
pkg/mod/github.com/antavelos/terminews@v1.2.0/ctrl.go:355:4: g.Execute undefined (type *gocui.Gui has no field or method Execute)
pkg/mod/github.com/antavelos/terminews@v1.2.0/ctrl.go:379:5: g.Execute undefined (type *gocui.Gui has no field or method Execute)
pkg/mod/github.com/antavelos/terminews@v1.2.0/ctrl.go:431:8: g.Execute undefined (type *gocui.Gui has no field or method Execute)
pkg/mod/github.com/antavelos/terminews@v1.2.0/ctrl.go:437:8: g.Execute undefined (type *gocui.Gui has no field or method Execute)
pkg/mod/github.com/antavelos/terminews@v1.2.0/ctrl.go:455:4: g.Execute undefined (type *gocui.Gui has no field or method Execute)
pkg/mod/github.com/antavelos/terminews@v1.2.0/ctrl.go:614:4: g.Execute undefined (type *gocui.Gui has no field or method Execute)
pkg/mod/github.com/antavelos/terminews@v1.2.0/main.go:193:3: g.Execute undefined (type *gocui.Gui has no field or method Execute)
```

go version: 1.13.8
$GOPATH and $GOROOT is working

**Comment by creekorful** [comment] 2021-01-09 09:26
Are you still getting the issue? It's working fine for me.
The error you are getting has been fixed by: https://github.com/antavelos/terminews/commit/622a413e68027f7c26b38ac6512966660e82366f

**Comment by creekorful** [comment] 2021-03-09 19:56
I'm closing it since there's no news, feel free to open the issue if the problem is not solved.

Cheers!

**Closed by creekorful** 2021-03-09 19:56 UTC
